apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  CURRENT_HOST: "*"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBIT_HOST: rabbit
  MONGO_HOST: mongo
  MONGO_USER: askcos
  MONGO_PW: askcos
  MYSQL_HOST: mysql
  MYSQL_DATABASE: askcos_db
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: root
  KERAS_BACKEND: theano
  VERSION_NUMBER: "0.4.0"
  STATIC_URL: /static/
  ORGANIZATION: ""
  CONTACT_EMAIL: "mlpds_support@mit.edu"
  ALLOW_SMILES_RESOLVER: ""
  AUTH_MODIFY_BUYABLES: "True"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    upstream django {
      server 127.0.0.1:8000;
    }

    server {
      listen 80;

      # set the correct host(s) for your site
      server_name askcos;

      location /static/ {
          autoindex on;
          alias /static/;

      }

      location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
      }

      location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        proxy_read_timeout      600;
        uwsgi_read_timeout 600;

        proxy_redirect off;
        proxy_pass http://django;
      }
    }