version: '2'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './uwsgi_params:/etc/nginx/uwsgi_params'
      - '../askcos/askcos_site/static:/static'
    ports:
      - '80:80'
      - '443:443'

  app:
    image: askcos
    hostname: app
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano uwsgi --socket :8000 --master --processes=4 --wsgi-file /home/askcos/ASKCOS/askcos/wsgi.py"
    expose:
      - '8000'
    depends_on:
      - redis
      - rabbit

  te_coordinator:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 2 -Q te_coordinator"
    depends_on:
      - redis
      - rabbit

  sc_coordinator:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 2 -Q sc_coordinator"
    depends_on:
      - redis
      - rabbit

  ft_worker:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 2 -Q ft_worker"
    depends_on:
      - redis
      - rabbit

  cr_coordinator:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 2 -Q cr_coordinator"
    depends_on:
      - redis
      - rabbit

  cr_network_worker:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 2 -Q cr_network_worker"
    depends_on:
      - redis
      - rabbit

  tb_coordinator_mcts:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 2 -Q tb_coordinator_mcts"
    depends_on:
      - redis
      - rabbit

  tb_c_worker:
    image: askcos
    env_file:
      - .env
    command: bash -c "source activate askcos && KERAS_BACKEND=theano celery -A askcos_site worker -c 10 -Q tb_c_worker"
    depends_on:
      - redis
      - rabbit

  redis:
    image: redis
    hostname: redis
    expose:
      - '6379'
    volumes:
      - 'redisdata:/data'

  rabbit:
    image: rabbitmq
    hostname: rabbit
    expose:
      - '5672'

volumes:
  redisdata:
