version: '2.2'
services:
  nginx:
    image: nginx:1.17.6
    restart: always
    depends_on:
      - app
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './uwsgi_params:/etc/nginx/uwsgi_params'
      - './askcos.ssl.cert:/etc/ssl/certs/askcos.ssl.cert'
      - './askcos.ssl.key:/etc/ssl/private/askcos.ssl.key'
      - 'staticdata:/static'
    ports:
      - '80:80'
      - '443:443'

  mysql:
    image: mysql:5.7
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - 'mysql_data:/var/lib/mysql'
    expose:
      - '3306'

  mongo:
    image: mongo:4.2.2
    hostname: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - 'mongo_data:/data/db'

  app:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    hostname: app
    restart: always
    env_file:
      - .env
      - customization
    command: bash -c "uwsgi --socket :8000 --master --processes=4 --wsgi-file /usr/local/ASKCOS/askcos/wsgi.py"
    expose:
      - '8000'
    volumes:
      - 'staticdata:/usr/local/ASKCOS/askcos/askcos_site/static'
      - 'docdata:/usr/local/ASKCOS/docs/_build/html'
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  te_coordinator:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q te_coordinator -n te_coordinator@%h"
    depends_on:
      - redis
      - rabbit

  sc_coordinator:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q sc_coordinator -n sc_coordinator@%h"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  ft_worker:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q ft_worker -n ft_worker@%h"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  cr_coordinator:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q cr_coordinator -n cr_coordinator@%h"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  cr_network_worker:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 2 -Q cr_network_worker -n cr_network_worker@%h"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  tb_coordinator_mcts:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q tb_coordinator_mcts -n tb_coordinator_mcts@%h --pool=gevent --without-heartbeat"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  tb_c_worker:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q tb_c_worker -n tb_c_worker@%h --pool=gevent --without-heartbeat"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  tb_c_worker_preload:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q tb_c_worker_preload -n tb_c_worker_preload@%h"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  sites_worker:
    image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A askcos_site worker -c 1 -Q sites_worker --pool=gevent -n sites_worker@%h"
    depends_on:
      - redis
      - rabbit
      - mysql
      - mongo

  template_relevance_reaxys:
    image: tensorflow/serving
    restart: always
    volumes:
      - ./models/template_relevance/reaxys:/models/template_relevance/1
    environment:
      - MODEL_NAME=template_relevance
    ports:
      - 8501:8501

  redis:
    image: redis:5.0.7
    hostname: redis
    env_file:
      - .env
    restart: always
    expose:
      - '${REDIS_PORT}'
    volumes:
      - 'redisdata:/data'
    command: redis-server --port ${REDIS_PORT}

  rabbit:
    image: rabbitmq:3.8.2
    hostname: rabbit
    env_file:
      - .env
    restart: always
    expose:
      - '${RABBITMQ_NODE_PORT}'

volumes:
  redisdata:
  mysql_data:
  mongo_data:
  staticdata:
