apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-coordinator-mcts
  labels:
    app: tb-coordinator-mcts
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: tb-coordinator-mcts
  template:
    metadata:
      labels:
        pod: tb-coordinator-mcts
    spec:
      containers:
        - name: tb-coordinator-mcts
          image: registry.gitlab.com/mlpds_mit/askcos/askcos:0.4.1
          command: ["/bin/bash"]
          args: ["-c", "celery -A askcos_site worker -c 1 -Q tb_coordinator_mcts -n tb_coordinator_mcts@%h --pool gevent --without-heartbeat"]
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            requests:
              memory: "5Gi"
      imagePullSecrets:
        - name: regcred
